name: Ledger
version: '1.0-SNAPSHOT'
main: oschwa.ledger.Ledger
api-version: '1.21'
author: oschwa
commands:
  new:
    description: create new Ledger configuration.
    usage: /new
  scrap:
    description: remove existing Ledger configuration.
    usage: /scrap
  man:
    description: view Ledger manual.
    usage: /man
  leave:
    description: leave another player's Ledger.
    usage: /leave
  add:
    description: add another player to your Ledger configuration.
    usage: /add [player name]
  list:
    description: list all players in active Ledger.
    usage: /list
  remove:
    description: remove a player from an active Ledger.
    usage: /remove [player name]
